#!/usr/bin/env python
import sys
import argparse
from collections import defaultdict
from utils import read_ttable
from pprint import pprint

def dot(w, v):
    s = 0.0
    for k in set(w.keys()) & set(v.keys()):
        s += w[k] * v[k]
    return s

parser = argparse.ArgumentParser()
parser.add_argument('--input', '-i', default='data/dev+test.input')
parser.add_argument('--ttable', '-t', default='data/ttable')
args = parser.parse_args()

translation_table = read_ttable(args.ttable)
weights = {'log_prob_tgs': 0.9,
           "log_prob_sgt": 0.1}

for line in open(args.input):
    left_context, phrase, right_context = [part.strip() for part in line.decode('utf-8').strip().split('|||')]
    candidates = [target for target, features in sorted(translation_table[phrase].iteritems(), key=lambda (t, f): dot(f, weights), reverse=True)]
    print ' ||| '.join(candidates).encode('utf-8')

    
    #break
