#!/bin/sh


cat xaa > output.txt
cat xab >> output.txt
cat xac >> output.txt
cat xad >> output.txt
cat xae >> output.txt
cat xaf >> output.txt
cat xag >> output.txt
cat xah >> output.txt
cat xai >> output.txt
cat xaj >> output.txt
cat xak >> output.txt
cat xal >> output.txt
cat xam >> output.txt
cat xan >> output.txt
cat xao >> output.txt
cat xap >> output.txt
cat xaq >> output.txt
cat xar >> output.txt
cat xas >> output.txt
cat xat >> output.txt
cat xau >> output.txt
cat xav >> output.txt
cat xaw >> output.txt
cat xax >> output.txt
cat xay >> output.txt
cat xaz >> output.txt

cat xba >> output.txt
cat xbb >> output.txt
cat xbc >> output.txt
cat xbd >> output.txt
cat xbe >> output.txt
cat xbf >> output.txt
cat xbg >> output.txt
cat xbh >> output.txt
cat xbi >> output.txt
cat xbj >> output.txt
cat xbk >> output.txt
cat xbl >> output.txt
cat xbm >> output.txt
cat xbn >> output.txt
cat xbo >> output.txt
cat xbp >> output.txt
cat xbq >> output.txt
cat xbr >> output.txt
cat xbs >> output.txt
cat xbt >> output.txt
cat xbu >> output.txt
cat xbv >> output.txt
cat xbw >> output.txt
cat xbx >> output.txt
cat xby >> output.txt
cat xbz >> output.txt

cat xca >> output.txt
cat xcb >> output.txt
cat xcc >> output.txt
